# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 900)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/key-6-128.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("#logoFrame {\n"
"    image: url(:/icon/icon/key-48.ico);\n"
"    border-bottom: 1px solid #fff;\n"
"}\n"
"\n"
"/* Style for menu widget  */\n"
"#menuWidget {\n"
"    background-color: #353535;\n"
"}\n"
"\n"
"/* Style for QPushButton in menu widget  */\n"
"#menuWidget QPushButton {\n"
"    color: #000;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"    border: none;\n"
"    background-color: #fff;\n"
"    font-size: 14px;\n"
"    border: 5px solid #353535;\n"
"    height: 25px;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"/* Style for QPushButton*/\n"
"QPushButton {\n"
"    text-align: center;\n"
"    padding-left: 15px;\n"
"    border: none;\n"
"    background-color: #fff;\n"
"    font-size: 14px;\n"
"    border: 5px solid #353535;\n"
"    height: 25px;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"#menuWidget QPushButton:hover {\n"
"    background-color: #e3e3e3;\n"
"}\n"
"\n"
"\n"
"#menuWidget QPushButton:checked {\n"
"    background-color: #0055ff;\n"
"    color: #fff;\n"
"}\n"
"\n"
"/* Style for main widget */\n"
"#stackedWidget {\n"
"    background-color: #f4f5f8;\n"
"}\n"
"\n"
"/* Style for QLabel in main widget */\n"
"#stackedWidget QLabel {\n"
"    font-size: 14px;\n"
"    font-family: \"Segoe UI Semibold\";\n"
"}\n"
"\n"
"/* Style for QLineEdit and QSpinBox in main widget */\n"
"#stackedWidget QLineEdit, #stackedWidget QSpinBox {\n"
"    border: 1px solid #353535;\n"
"    border-radius: 3px;\n"
"    padding: 5px 10px;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"/* style for  QSpinBox*/\n"
"#stackedWidget QSpinBox::up-arrow {\n"
"    image: url(:/icon/icon/arrow-146-48.ico);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"#stackedWidget QSpinBox::down-arrow {\n"
"    image: url(:/icon/icon/arrow-208-48.ico);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"#stackedWidget QSpinBox::down-button, \n"
"#stackedWidget QSpinBox::up-button {\n"
"    border: none;\n"
"    width: 30px;\n"
"}\n"
"\n"
"#stackedWidget QSpinBox::down-button:hover, \n"
"#stackedWidget QSpinBox::up-button:hover {\n"
"    background-color: rgb(176, 176, 176);\n"
"}\n"
"\n"
"#stackedWidget QSpinBox::down-button:pressed, \n"
"#stackedWidget QSpinBox::up-button:pressed {\n"
"    background-color: rgb(78, 88, 121);\n"
"}\n"
"\n"
"/* Style for QPushButton in main widget */\n"
"#stackedWidget QPushButton {\n"
"    border: none;\n"
"    font-size: 16px;\n"
"    border-radius: 3px;\n"
"    color: #fff;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"#stackedWidget QPushButton:pressed {\n"
"    padding-left: 20px;\n"
"}\n"
"\n"
"/* Style for sepcial QPushButton in main widget */\n"
"#confEditBtn,\n"
"#generateCopyBtn, \n"
"#generateRestBtn,\n"
"#showSearchBtn\n"
"{\n"
"    background-color: #3554d1;\n"
"}\n"
"\n"
"#confEditBtn:hover, #confEditBtn:pressed, \n"
"#generateCopyBtn:hover,  #generateCopyBtn:pressed, \n"
"#generateRestBtn:hover,  #generateRestBtn:pressed, \n"
"#showSearchBtn:hover,  #showSearchBtn:pressed \n"
"{\n"
"    background-color: #0000ff;\n"
"}\n"
"\n"
"#confSaveBtn,\n"
"#generateSaveBtn, \n"
"#generateCreateBtn\n"
"{\n"
"    background-color: #00aa7f;\n"
"}\n"
"\n"
"#confSaveBtn:hover, #confSaveBtn:pressed, \n"
"#generateSaveBtn:hover, #generateSaveBtn:pressed,\n"
"#generateCreateBtn:hover, #generateCreateBtn:pressed \n"
"{\n"
"    background-color: #00aa00;\n"
"}\n"
"\n"
"#confRefreshBtn,\n"
" #showRefreshBtn\n"
"{\n"
"    background-color: #E59866;\n"
"}\n"
"\n"
"\n"
"#confRefreshBtn:hover, #confRefreshBtn:pressed, \n"
"#showRefreshBtn:hover, #showRefreshBtn:pressed\n"
"{\n"
"    background-color: #DC7633;\n"
"}\n"
"\n"
"/* Style for QCheckBox in main widget */\n"
"QCheckBox {\n"
"    spacing: 10px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    image: url(:/icon/icon/checkbox_unchecked.ico);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    image: url(:/icon/icon/checkbox_checked.ico);\n"
"}\n"
"\n"
"\n"
"/* Style for QFrame */\n"
"#resultFrame {\n"
"    border-radius: 5px;\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"/* Style for QTableWidget */\n"
"#tableWidget QHeaderView, #tableWidget   {\n"
"    border:0px;\n"
"    background-color:  #fff;\n"
"    border-radius:5px;\n"
"    text-align:left;\n"
"}\n"
"\n"
"#tableWidget QHeaderView::section{\n"
"    font-family:\"Times New Roman\", \"Times\", \"serif\";\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    text-align:left;\n"
"    border-radius:14px;\n"
"    border-bottom:1px solid #353535;\n"
"    border-top:1px solid #353535;\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"#tableWidget::item:selected {\n"
"    background-color: #55aaff;\n"
"}\n"
"\n"
"#tableWidget::item{\n"
"    border-bottom:1px solid #d0c6ff;\n"
"    padding-left: 10px;\n"
"    color: black;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.menuWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.menuWidget.setMinimumSize(QtCore.QSize(200, 0))
        self.menuWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.menuWidget.setObjectName("menuWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.menuWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_12 = QtWidgets.QLabel(parent=self.menuWidget)
        self.label_12.setMinimumSize(QtCore.QSize(0, 100))
        self.label_12.setStyleSheet("color: #fff;\n"
"font-size: 32px;\n"
"font-weight: bold;")
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.btn_menu_1 = QtWidgets.QPushButton(parent=self.menuWidget)
        self.btn_menu_1.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_menu_1.setMaximumSize(QtCore.QSize(16777215, 35))
        self.btn_menu_1.setCheckable(True)
        self.btn_menu_1.setChecked(True)
        self.btn_menu_1.setAutoExclusive(True)
        self.btn_menu_1.setObjectName("btn_menu_1")
        self.verticalLayout.addWidget(self.btn_menu_1)
        self.btn_menu_2 = QtWidgets.QPushButton(parent=self.menuWidget)
        self.btn_menu_2.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_menu_2.setMaximumSize(QtCore.QSize(16777215, 35))
        self.btn_menu_2.setCheckable(True)
        self.btn_menu_2.setAutoExclusive(True)
        self.btn_menu_2.setObjectName("btn_menu_2")
        self.verticalLayout.addWidget(self.btn_menu_2)
        self.btn_menu_3 = QtWidgets.QPushButton(parent=self.menuWidget)
        self.btn_menu_3.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_menu_3.setMaximumSize(QtCore.QSize(16777215, 35))
        self.btn_menu_3.setCheckable(True)
        self.btn_menu_3.setAutoExclusive(True)
        self.btn_menu_3.setObjectName("btn_menu_3")
        self.verticalLayout.addWidget(self.btn_menu_3)
        self.btn_menu_4 = QtWidgets.QPushButton(parent=self.menuWidget)
        self.btn_menu_4.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_menu_4.setMaximumSize(QtCore.QSize(16777215, 35))
        self.btn_menu_4.setCheckable(True)
        self.btn_menu_4.setAutoExclusive(True)
        self.btn_menu_4.setObjectName("btn_menu_4")
        self.verticalLayout.addWidget(self.btn_menu_4)
        spacerItem = QtWidgets.QSpacerItem(20, 574, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.exitBtn = QtWidgets.QPushButton(parent=self.menuWidget)
        self.exitBtn.setMinimumSize(QtCore.QSize(0, 40))
        self.exitBtn.setMaximumSize(QtCore.QSize(16777215, 35))
        self.exitBtn.setStyleSheet("#exitBtn {\n"
"    color: #943e3e;\n"
"    text-align: center;\n"
"    padding-left: 0;\n"
"}\n"
"\n"
"#exitBtn:pressed {\n"
"    padding-left: 10px;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/logout-48.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.exitBtn.setIcon(icon1)
        self.exitBtn.setObjectName("exitBtn")
        self.verticalLayout.addWidget(self.exitBtn)
        self.gridLayout.addWidget(self.menuWidget, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setStyleSheet("color: #000;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.layoutWidget_6 = QtWidgets.QWidget(parent=self.page_3)
        self.layoutWidget_6.setGeometry(QtCore.QRect(40, 30, 921, 32))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget_6)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_4 = QtWidgets.QLabel(parent=self.layoutWidget_6)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 1)
        self.keyword_search_pet = QtWidgets.QLineEdit(parent=self.layoutWidget_6)
        self.keyword_search_pet.setStyleSheet("background-color: #fff;")
        self.keyword_search_pet.setObjectName("keyword_search_pet")
        self.gridLayout_5.addWidget(self.keyword_search_pet, 0, 1, 1, 1)
        self.btn_search_pet = QtWidgets.QPushButton(parent=self.layoutWidget_6)
        self.btn_search_pet.setMinimumSize(QtCore.QSize(150, 30))
        self.btn_search_pet.setMaximumSize(QtCore.QSize(150, 32))
        self.btn_search_pet.setStyleSheet("background-color: #0a31d1;\n"
"font-weight: bold;\n"
"color: #fff;")
        self.btn_search_pet.setObjectName("btn_search_pet")
        self.gridLayout_5.addWidget(self.btn_search_pet, 0, 2, 1, 1)
        self.widget_3 = QtWidgets.QWidget(parent=self.page_3)
        self.widget_3.setGeometry(QtCore.QRect(40, 90, 921, 791))
        self.widget_3.setStyleSheet("QTableWidget {\n"
"    background-color: #fff;\n"
"}")
        self.widget_3.setObjectName("widget_3")
        self.layoutWidget_3 = QtWidgets.QWidget(parent=self.widget_3)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 0, 921, 791))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_21 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        self.label_21.setMinimumSize(QtCore.QSize(0, 50))
        self.label_21.setStyleSheet("font-size:24px;\n"
"font-weight: bold;")
        self.label_21.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_4.addWidget(self.label_21)
        self.pet_table = QtWidgets.QTableWidget(parent=self.layoutWidget_3)
        self.pet_table.setMinimumSize(QtCore.QSize(0, 150))
        self.pet_table.setSizeIncrement(QtCore.QSize(0, 150))
        self.pet_table.setStyleSheet("QHeaderView::section {\n"
"    font-weight: bold;\n"
"    background-color: #000;\n"
"    color: #fff;\n"
"}")
        self.pet_table.setObjectName("pet_table")
        self.pet_table.setColumnCount(12)
        self.pet_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pet_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pet_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pet_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pet_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pet_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pet_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pet_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pet_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pet_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pet_table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pet_table.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pet_table.setHorizontalHeaderItem(11, item)
        self.pet_table.horizontalHeader().setCascadingSectionResizes(False)
        self.pet_table.horizontalHeader().setSortIndicatorShown(False)
        self.pet_table.horizontalHeader().setStretchLastSection(True)
        self.pet_table.verticalHeader().setCascadingSectionResizes(False)
        self.pet_table.verticalHeader().setSortIndicatorShown(False)
        self.pet_table.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_4.addWidget(self.pet_table)
        self.stackedWidget.addWidget(self.page_3)
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("")
        self.page.setObjectName("page")
        self.layoutWidget = QtWidgets.QWidget(parent=self.page)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 30, 921, 32))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.keyword_search = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.keyword_search.setStyleSheet("background-color: #fff;")
        self.keyword_search.setObjectName("keyword_search")
        self.gridLayout_3.addWidget(self.keyword_search, 0, 1, 1, 1)
        self.btn_search = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn_search.setMinimumSize(QtCore.QSize(150, 30))
        self.btn_search.setMaximumSize(QtCore.QSize(150, 32))
        self.btn_search.setStyleSheet("background-color: #0a31d1;\n"
"font-weight: bold;\n"
"color: #fff;")
        self.btn_search.setObjectName("btn_search")
        self.gridLayout_3.addWidget(self.btn_search, 0, 2, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.page)
        self.layoutWidget1.setGeometry(QtCore.QRect(180, 70, 621, 227))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.chi_tiet_thu_cung = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.chi_tiet_thu_cung.setContentsMargins(0, 0, 0, 0)
        self.chi_tiet_thu_cung.setObjectName("chi_tiet_thu_cung")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label.setStyleSheet("font-size:24px;\n"
"font-weight: bold;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.chi_tiet_thu_cung.addWidget(self.label)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_10 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_10.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.lbl_ten_kh = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.lbl_ten_kh.setText("")
        self.lbl_ten_kh.setObjectName("lbl_ten_kh")
        self.horizontalLayout_2.addWidget(self.lbl_ten_kh)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_11 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_11.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.lbl_sdt = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.lbl_sdt.setText("")
        self.lbl_sdt.setObjectName("lbl_sdt")
        self.horizontalLayout_3.addWidget(self.lbl_sdt)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.chi_tiet_thu_cung.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_14 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_14.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_6.addWidget(self.label_14)
        self.lbl_ten = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.lbl_ten.setText("")
        self.lbl_ten.setObjectName("lbl_ten")
        self.horizontalLayout_6.addWidget(self.lbl_ten)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_16 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_16.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_7.addWidget(self.label_16)
        self.lbl_ma_so = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.lbl_ma_so.setText("")
        self.lbl_ma_so.setObjectName("lbl_ma_so")
        self.horizontalLayout_7.addWidget(self.lbl_ma_so)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_7)
        self.chi_tiet_thu_cung.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_23 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_23.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_17.addWidget(self.label_23)
        self.lbl_giong_loai = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.lbl_giong_loai.setText("")
        self.lbl_giong_loai.setObjectName("lbl_giong_loai")
        self.horizontalLayout_17.addWidget(self.lbl_giong_loai)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_25 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_25.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_18.addWidget(self.label_25)
        self.lbl_ngay_sinh = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.lbl_ngay_sinh.setText("")
        self.lbl_ngay_sinh.setObjectName("lbl_ngay_sinh")
        self.horizontalLayout_18.addWidget(self.lbl_ngay_sinh)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_18)
        self.chi_tiet_thu_cung.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_18 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_18.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_9.addWidget(self.label_18)
        self.lbl_mau_sac = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.lbl_mau_sac.setText("")
        self.lbl_mau_sac.setObjectName("lbl_mau_sac")
        self.horizontalLayout_9.addWidget(self.lbl_mau_sac)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_20 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_20.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_10.addWidget(self.label_20)
        self.lbl_can_nang = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.lbl_can_nang.setText("")
        self.lbl_can_nang.setObjectName("lbl_can_nang")
        self.horizontalLayout_10.addWidget(self.lbl_can_nang)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_10)
        self.chi_tiet_thu_cung.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_22 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_22.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_12.addWidget(self.label_22)
        self.lbl_chieu_dai = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.lbl_chieu_dai.setText("")
        self.lbl_chieu_dai.setObjectName("lbl_chieu_dai")
        self.horizontalLayout_12.addWidget(self.lbl_chieu_dai)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_24 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_24.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_13.addWidget(self.label_24)
        self.lbl_chieu_cao = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.lbl_chieu_cao.setText("")
        self.lbl_chieu_cao.setObjectName("lbl_chieu_cao")
        self.horizontalLayout_13.addWidget(self.lbl_chieu_cao)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_13)
        self.chi_tiet_thu_cung.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_26 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_26.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_15.addWidget(self.label_26)
        self.lbl_mo_ta = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.lbl_mo_ta.setText("")
        self.lbl_mo_ta.setObjectName("lbl_mo_ta")
        self.horizontalLayout_15.addWidget(self.lbl_mo_ta)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_15)
        self.chi_tiet_thu_cung.addLayout(self.horizontalLayout_14)
        self.layoutWidget2 = QtWidgets.QWidget(parent=self.page)
        self.layoutWidget2.setGeometry(QtCore.QRect(40, 320, 921, 37))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.danh_sach_btn = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.danh_sach_btn.setContentsMargins(0, 0, 0, 0)
        self.danh_sach_btn.setObjectName("danh_sach_btn")
        self.btn_edit = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.btn_edit.setStyleSheet("background-color: #337aff;\n"
"font-weight: bold;\n"
"color: #fff;")
        self.btn_edit.setObjectName("btn_edit")
        self.danh_sach_btn.addWidget(self.btn_edit)
        self.btn_lich_hen = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.btn_lich_hen.setStyleSheet("background-color: #ff6133;\n"
"font-weight: bold;\n"
"color: #fff;")
        self.btn_lich_hen.setObjectName("btn_lich_hen")
        self.danh_sach_btn.addWidget(self.btn_lich_hen)
        self.btn_che_do_an_uong = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.btn_che_do_an_uong.setStyleSheet("background-color: #ffd433;\n"
"font-weight: bold;\n"
"color: #fff;")
        self.btn_che_do_an_uong.setObjectName("btn_che_do_an_uong")
        self.danh_sach_btn.addWidget(self.btn_che_do_an_uong)
        self.btn_hoat_dong = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.btn_hoat_dong.setStyleSheet("background-color: #8d33ff;\n"
"font-weight: bold;\n"
"color: #fff;")
        self.btn_hoat_dong.setObjectName("btn_hoat_dong")
        self.danh_sach_btn.addWidget(self.btn_hoat_dong)
        self.btn_cham_soc_suc_khoe = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.btn_cham_soc_suc_khoe.setStyleSheet("background-color: #ff33dd;\n"
"font-weight: bold;\n"
"color: #fff;")
        self.btn_cham_soc_suc_khoe.setObjectName("btn_cham_soc_suc_khoe")
        self.danh_sach_btn.addWidget(self.btn_cham_soc_suc_khoe)
        self.btn_chi_phi = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.btn_chi_phi.setStyleSheet("background-color: #363636;\n"
"font-weight: bold;\n"
"color: #fff;")
        self.btn_chi_phi.setObjectName("btn_chi_phi")
        self.danh_sach_btn.addWidget(self.btn_chi_phi)
        self.thong_tin_khac = QtWidgets.QScrollArea(parent=self.page)
        self.thong_tin_khac.setGeometry(QtCore.QRect(40, 380, 921, 500))
        self.thong_tin_khac.setMaximumSize(QtCore.QSize(16777215, 500))
        self.thong_tin_khac.setStyleSheet("background-color: #fff;")
        self.thong_tin_khac.setWidgetResizable(True)
        self.thong_tin_khac.setObjectName("thong_tin_khac")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 902, 972))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_5.setMinimumSize(QtCore.QSize(0, 30))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_5.setStyleSheet("font-size: 18px;\n"
"font-weight: bold;")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.expense_table = QtWidgets.QTableWidget(parent=self.scrollAreaWidgetContents)
        self.expense_table.setMinimumSize(QtCore.QSize(0, 150))
        self.expense_table.setMaximumSize(QtCore.QSize(16777215, 150))
        self.expense_table.setStyleSheet("QHeaderView::section {\n"
"    font-weight: bold;\n"
"    background-color: #000;\n"
"    color: #fff;\n"
"}")
        self.expense_table.setObjectName("expense_table")
        self.expense_table.setColumnCount(5)
        self.expense_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.expense_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.expense_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.expense_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.expense_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.expense_table.setHorizontalHeaderItem(4, item)
        self.expense_table.horizontalHeader().setDefaultSectionSize(150)
        self.expense_table.horizontalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.expense_table, 8, 0, 1, 1)
        self.exercise_table = QtWidgets.QTableWidget(parent=self.scrollAreaWidgetContents)
        self.exercise_table.setMinimumSize(QtCore.QSize(0, 150))
        self.exercise_table.setMaximumSize(QtCore.QSize(16777215, 150))
        self.exercise_table.setStyleSheet("QHeaderView::section {\n"
"    font-weight: bold;\n"
"    background-color: #000;\n"
"    color: #fff;\n"
"}")
        self.exercise_table.setObjectName("exercise_table")
        self.exercise_table.setColumnCount(5)
        self.exercise_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.exercise_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.exercise_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.exercise_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.exercise_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.exercise_table.setHorizontalHeaderItem(4, item)
        self.exercise_table.horizontalHeader().setDefaultSectionSize(200)
        self.exercise_table.horizontalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.exercise_table, 6, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_7.setMinimumSize(QtCore.QSize(0, 30))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_7.setStyleSheet("font-size: 18px;\n"
"font-weight: bold;")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_6.setMinimumSize(QtCore.QSize(0, 30))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_6.setStyleSheet("font-size: 18px;\n"
"font-weight: bold;")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_9.setMinimumSize(QtCore.QSize(0, 30))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_9.setStyleSheet("font-size: 18px;\n"
"font-weight: bold;")
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 9, 0, 1, 1)
        self.health_table = QtWidgets.QTableWidget(parent=self.scrollAreaWidgetContents)
        self.health_table.setMinimumSize(QtCore.QSize(0, 150))
        self.health_table.setSizeIncrement(QtCore.QSize(0, 150))
        self.health_table.setStyleSheet("QHeaderView::section {\n"
"    font-weight: bold;\n"
"    background-color: #000;\n"
"    color: #fff;\n"
"}")
        self.health_table.setObjectName("health_table")
        self.health_table.setColumnCount(6)
        self.health_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.health_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.health_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.health_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.health_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.health_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.health_table.setHorizontalHeaderItem(5, item)
        self.health_table.horizontalHeader().setCascadingSectionResizes(False)
        self.health_table.horizontalHeader().setSortIndicatorShown(False)
        self.health_table.horizontalHeader().setStretchLastSection(True)
        self.health_table.verticalHeader().setCascadingSectionResizes(False)
        self.health_table.verticalHeader().setSortIndicatorShown(False)
        self.health_table.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.health_table, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_8.setMinimumSize(QtCore.QSize(0, 30))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_8.setStyleSheet("font-size: 18px;\n"
"font-weight: bold;")
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 7, 0, 1, 1)
        self.feeding_table = QtWidgets.QTableWidget(parent=self.scrollAreaWidgetContents)
        self.feeding_table.setMinimumSize(QtCore.QSize(0, 150))
        self.feeding_table.setMaximumSize(QtCore.QSize(16777215, 150))
        self.feeding_table.setStyleSheet("QHeaderView::section {\n"
"    font-weight: bold;\n"
"    background-color: #000;\n"
"    color: #fff;\n"
"}")
        self.feeding_table.setObjectName("feeding_table")
        self.feeding_table.setColumnCount(5)
        self.feeding_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.feeding_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.feeding_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.feeding_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.feeding_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.feeding_table.setHorizontalHeaderItem(4, item)
        self.feeding_table.horizontalHeader().setDefaultSectionSize(200)
        self.feeding_table.horizontalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.feeding_table, 4, 0, 1, 1)
        self.appointment_table = QtWidgets.QTableWidget(parent=self.scrollAreaWidgetContents)
        self.appointment_table.setMinimumSize(QtCore.QSize(0, 150))
        self.appointment_table.setMaximumSize(QtCore.QSize(16777215, 150))
        self.appointment_table.setStyleSheet("QHeaderView::section {\n"
"    font-weight: bold;\n"
"    background-color: #000;\n"
"    color: #fff;\n"
"}")
        self.appointment_table.setObjectName("appointment_table")
        self.appointment_table.setColumnCount(4)
        self.appointment_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.appointment_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.appointment_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.appointment_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.appointment_table.setHorizontalHeaderItem(3, item)
        self.appointment_table.horizontalHeader().setDefaultSectionSize(200)
        self.appointment_table.horizontalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.appointment_table, 10, 0, 1, 1)
        self.thong_tin_khac.setWidget(self.scrollAreaWidgetContents)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.layoutWidget_5 = QtWidgets.QWidget(parent=self.page_2)
        self.layoutWidget_5.setGeometry(QtCore.QRect(40, 30, 921, 32))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_5)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.keyword_search_customer = QtWidgets.QLineEdit(parent=self.layoutWidget_5)
        self.keyword_search_customer.setStyleSheet("background-color: #fff;")
        self.keyword_search_customer.setObjectName("keyword_search_customer")
        self.gridLayout_4.addWidget(self.keyword_search_customer, 0, 1, 1, 1)
        self.btn_search_customer = QtWidgets.QPushButton(parent=self.layoutWidget_5)
        self.btn_search_customer.setMinimumSize(QtCore.QSize(150, 30))
        self.btn_search_customer.setMaximumSize(QtCore.QSize(150, 32))
        self.btn_search_customer.setStyleSheet("background-color: #0a31d1;\n"
"font-weight: bold;\n"
"color: #fff;")
        self.btn_search_customer.setObjectName("btn_search_customer")
        self.gridLayout_4.addWidget(self.btn_search_customer, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget_5)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.btn_add_customer = QtWidgets.QPushButton(parent=self.layoutWidget_5)
        self.btn_add_customer.setMinimumSize(QtCore.QSize(200, 30))
        self.btn_add_customer.setMaximumSize(QtCore.QSize(150, 32))
        self.btn_add_customer.setStyleSheet("background-color: #2ecc71;\n"
"font-weight: bold;\n"
"color: #fff;")
        self.btn_add_customer.setObjectName("btn_add_customer")
        self.gridLayout_4.addWidget(self.btn_add_customer, 0, 3, 1, 1)
        self.widget = QtWidgets.QWidget(parent=self.page_2)
        self.widget.setGeometry(QtCore.QRect(40, 90, 921, 791))
        self.widget.setStyleSheet("QTableWidget {\n"
"    background-color: #fff;\n"
"}")
        self.widget.setObjectName("widget")
        self.layoutWidget3 = QtWidgets.QWidget(parent=self.widget)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 0, 921, 791))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_13 = QtWidgets.QLabel(parent=self.layoutWidget3)
        self.label_13.setMinimumSize(QtCore.QSize(0, 50))
        self.label_13.setStyleSheet("font-size:24px;\n"
"font-weight: bold;")
        self.label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.customer_table = QtWidgets.QTableWidget(parent=self.layoutWidget3)
        self.customer_table.setMinimumSize(QtCore.QSize(0, 150))
        self.customer_table.setSizeIncrement(QtCore.QSize(0, 150))
        self.customer_table.setStyleSheet("QHeaderView::section {\n"
"    font-weight: bold;\n"
"    background-color: #000;\n"
"    color: #fff;\n"
"}")
        self.customer_table.setObjectName("customer_table")
        self.customer_table.setColumnCount(4)
        self.customer_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.customer_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.customer_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.customer_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.customer_table.setHorizontalHeaderItem(3, item)
        self.customer_table.horizontalHeader().setCascadingSectionResizes(False)
        self.customer_table.horizontalHeader().setSortIndicatorShown(False)
        self.customer_table.horizontalHeader().setStretchLastSection(True)
        self.customer_table.verticalHeader().setCascadingSectionResizes(False)
        self.customer_table.verticalHeader().setSortIndicatorShown(False)
        self.customer_table.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.customer_table)
        self.stackedWidget.addWidget(self.page_2)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setStyleSheet("QDateEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 5px;\n"
"    height: 30px;\n"
"    padding-left: 10px;\n"
"    background-color: #fff;\n"
"}")
        self.page_4.setObjectName("page_4")
        self.widget_2 = QtWidgets.QWidget(parent=self.page_4)
        self.widget_2.setGeometry(QtCore.QRect(40, 100, 921, 791))
        self.widget_2.setStyleSheet("QTableWidget {\n"
"    background-color: #fff;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.layoutWidget_2 = QtWidgets.QWidget(parent=self.widget_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 921, 781))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_19 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        self.label_19.setMinimumSize(QtCore.QSize(0, 50))
        self.label_19.setStyleSheet("font-size:24px;\n"
"font-weight: bold;")
        self.label_19.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_3.addWidget(self.label_19)
        self.lbl_tong_doanh_thu = QtWidgets.QLabel(parent=self.layoutWidget_2)
        self.lbl_tong_doanh_thu.setMinimumSize(QtCore.QSize(0, 50))
        self.lbl_tong_doanh_thu.setStyleSheet("font-size:24px;\n"
"font-weight: bold;")
        self.lbl_tong_doanh_thu.setObjectName("lbl_tong_doanh_thu")
        self.verticalLayout_3.addWidget(self.lbl_tong_doanh_thu)
        self.total_expense_table = QtWidgets.QTableWidget(parent=self.layoutWidget_2)
        self.total_expense_table.setMinimumSize(QtCore.QSize(0, 150))
        self.total_expense_table.setSizeIncrement(QtCore.QSize(0, 150))
        self.total_expense_table.setStyleSheet("QHeaderView::section {\n"
"    font-weight: bold;\n"
"    background-color: #000;\n"
"    color: #fff;\n"
"}")
        self.total_expense_table.setObjectName("total_expense_table")
        self.total_expense_table.setColumnCount(5)
        self.total_expense_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.total_expense_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.total_expense_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.total_expense_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.total_expense_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.total_expense_table.setHorizontalHeaderItem(4, item)
        self.total_expense_table.horizontalHeader().setCascadingSectionResizes(False)
        self.total_expense_table.horizontalHeader().setSortIndicatorShown(False)
        self.total_expense_table.horizontalHeader().setStretchLastSection(True)
        self.total_expense_table.verticalHeader().setCascadingSectionResizes(False)
        self.total_expense_table.verticalHeader().setSortIndicatorShown(False)
        self.total_expense_table.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_3.addWidget(self.total_expense_table)
        self.layoutWidget4 = QtWidgets.QWidget(parent=self.page_4)
        self.layoutWidget4.setGeometry(QtCore.QRect(40, 30, 921, 34))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_15 = QtWidgets.QLabel(parent=self.layoutWidget4)
        self.label_15.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout.addWidget(self.label_15)
        self.date_from = QtWidgets.QDateEdit(parent=self.layoutWidget4)
        self.date_from.setMinimumSize(QtCore.QSize(180, 0))
        self.date_from.setMaximumSize(QtCore.QSize(200, 16777215))
        self.date_from.setObjectName("date_from")
        self.horizontalLayout.addWidget(self.date_from)
        self.label_17 = QtWidgets.QLabel(parent=self.layoutWidget4)
        self.label_17.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout.addWidget(self.label_17)
        self.date_to = QtWidgets.QDateEdit(parent=self.layoutWidget4)
        self.date_to.setMaximumSize(QtCore.QSize(200, 16777215))
        self.date_to.setObjectName("date_to")
        self.horizontalLayout.addWidget(self.date_to)
        self.btn_filter_expense = QtWidgets.QPushButton(parent=self.layoutWidget4)
        self.btn_filter_expense.setMinimumSize(QtCore.QSize(150, 30))
        self.btn_filter_expense.setMaximumSize(QtCore.QSize(150, 32))
        self.btn_filter_expense.setStyleSheet("background-color: #0a31d1;\n"
"font-weight: bold;\n"
"color: #fff;")
        self.btn_filter_expense.setObjectName("btn_filter_expense")
        self.horizontalLayout.addWidget(self.btn_filter_expense)
        self.btn_get_all_expense = QtWidgets.QPushButton(parent=self.layoutWidget4)
        self.btn_get_all_expense.setMinimumSize(QtCore.QSize(150, 30))
        self.btn_get_all_expense.setMaximumSize(QtCore.QSize(150, 32))
        self.btn_get_all_expense.setStyleSheet("background-color: #0a31d1;\n"
"font-weight: bold;\n"
"color: #fff;")
        self.btn_get_all_expense.setObjectName("btn_get_all_expense")
        self.horizontalLayout.addWidget(self.btn_get_all_expense)
        self.stackedWidget.addWidget(self.page_4)
        self.gridLayout.addWidget(self.stackedWidget, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pets shop"))
        self.label_12.setText(_translate("MainWindow", "Pets shop"))
        self.btn_menu_1.setText(_translate("MainWindow", "Trang chủ"))
        self.btn_menu_2.setText(_translate("MainWindow", "Danh sách khách hàng"))
        self.btn_menu_3.setText(_translate("MainWindow", "Danh sách thú cưng"))
        self.btn_menu_4.setText(_translate("MainWindow", "Thống kê doanh thu"))
        self.exitBtn.setText(_translate("MainWindow", "Exit"))
        self.label_4.setText(_translate("MainWindow", "Tìm kiếm"))
        self.btn_search_pet.setText(_translate("MainWindow", "Tìm kiếm"))
        self.label_21.setText(_translate("MainWindow", "Danh sách thú cưng"))
        item = self.pet_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "STT"))
        item = self.pet_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Khách hàng"))
        item = self.pet_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Điện thoại"))
        item = self.pet_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Mã số"))
        item = self.pet_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Tên"))
        item = self.pet_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Giống loài"))
        item = self.pet_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Ngày sinh"))
        item = self.pet_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Màu sắc"))
        item = self.pet_table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Cân nặng"))
        item = self.pet_table.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Chiều cao"))
        item = self.pet_table.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Chiều dài"))
        item = self.pet_table.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Mô tả"))
        self.label_2.setText(_translate("MainWindow", "Tìm kiếm"))
        self.btn_search.setText(_translate("MainWindow", "Tìm kiếm"))
        self.label.setText(_translate("MainWindow", "Thông tin thú cưng"))
        self.label_10.setText(_translate("MainWindow", "Khách hàng:"))
        self.label_11.setText(_translate("MainWindow", "Điện thoại:"))
        self.label_14.setText(_translate("MainWindow", "Tên:"))
        self.label_16.setText(_translate("MainWindow", "Mã số:"))
        self.label_23.setText(_translate("MainWindow", "Giống loài:"))
        self.label_25.setText(_translate("MainWindow", "Ngày sinh:"))
        self.label_18.setText(_translate("MainWindow", "Màu sắc:"))
        self.label_20.setText(_translate("MainWindow", "Cân nặng:"))
        self.label_22.setText(_translate("MainWindow", "Chiều dài:"))
        self.label_24.setText(_translate("MainWindow", "Chiều cao:"))
        self.label_26.setText(_translate("MainWindow", "Mô tả:"))
        self.btn_edit.setText(_translate("MainWindow", "Sửa"))
        self.btn_lich_hen.setText(_translate("MainWindow", "Lịch hẹn"))
        self.btn_che_do_an_uong.setText(_translate("MainWindow", "Chế độ ăn uống"))
        self.btn_hoat_dong.setText(_translate("MainWindow", "Hoạt động"))
        self.btn_cham_soc_suc_khoe.setText(_translate("MainWindow", "Chăm sóc sức khỏe"))
        self.btn_chi_phi.setText(_translate("MainWindow", "Chi phí"))
        self.label_5.setText(_translate("MainWindow", "Chế độ ăn uống"))
        item = self.expense_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "STT"))
        item = self.expense_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Hoạt động"))
        item = self.expense_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ngày phát sinh"))
        item = self.expense_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Chi phí"))
        item = self.expense_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Chi tiết"))
        item = self.exercise_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "STT"))
        item = self.exercise_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Hoạt động"))
        item = self.exercise_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ngày hoạt động"))
        item = self.exercise_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Thời gian hoạt động"))
        self.label_7.setText(_translate("MainWindow", "Chăm sóc sức khỏe"))
        self.label_6.setText(_translate("MainWindow", "Hoạt động thể chất"))
        self.label_9.setText(_translate("MainWindow", "Lịch hẹn"))
        item = self.health_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "STT"))
        item = self.health_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Loại vắc xin"))
        item = self.health_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ngày tiêm"))
        item = self.health_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Ngày khám"))
        item = self.health_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Tình trạng"))
        self.label_8.setText(_translate("MainWindow", "Chi phí"))
        item = self.feeding_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "STT"))
        item = self.feeding_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Loại thức ăn"))
        item = self.feeding_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ngày cho ăn"))
        item = self.feeding_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Trọng lượng"))
        item = self.appointment_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "STT"))
        item = self.appointment_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Ngày hẹn"))
        item = self.appointment_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Giờ hẹn"))
        item = self.appointment_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Mục đích"))
        self.btn_search_customer.setText(_translate("MainWindow", "Tìm kiếm"))
        self.label_3.setText(_translate("MainWindow", "Tìm kiếm"))
        self.btn_add_customer.setText(_translate("MainWindow", "Thêm khách hàng"))
        self.label_13.setText(_translate("MainWindow", "Danh sách khách hàng"))
        item = self.customer_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "STT"))
        item = self.customer_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tên"))
        item = self.customer_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Số điện thoại"))
        self.label_19.setText(_translate("MainWindow", "Thống kê doanh thu"))
        self.lbl_tong_doanh_thu.setText(_translate("MainWindow", "Tổng: 0đ"))
        item = self.total_expense_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "STT"))
        item = self.total_expense_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Hoạt động"))
        item = self.total_expense_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ngày phát sinh"))
        item = self.total_expense_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Chi phí"))
        item = self.total_expense_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Chi tiết"))
        self.label_15.setText(_translate("MainWindow", "Từ "))
        self.label_17.setText(_translate("MainWindow", "tới"))
        self.btn_filter_expense.setText(_translate("MainWindow", "Lọc"))
        self.btn_get_all_expense.setText(_translate("MainWindow", "Tất cả"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
