# Form implementation generated from reading ui file 'add_exercise.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddExerciseDialog(object):
    def setupUi(self, AddExerciseDialog):
        AddExerciseDialog.setObjectName("AddExerciseDialog")
        AddExerciseDialog.resize(330, 206)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddExerciseDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=AddExerciseDialog)
        self.titleLabel.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.categoryLabel_2 = QtWidgets.QLabel(parent=AddExerciseDialog)
        self.categoryLabel_2.setObjectName("categoryLabel_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.categoryLabel_2)
        self.activity_type = QtWidgets.QLineEdit(parent=AddExerciseDialog)
        self.activity_type.setObjectName("activity_type")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.activity_type)
        self.dateLabel = QtWidgets.QLabel(parent=AddExerciseDialog)
        self.dateLabel.setObjectName("dateLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.dateLabel)
        self.exercise_date = QtWidgets.QDateEdit(parent=AddExerciseDialog)
        self.exercise_date.setCalendarPopup(True)
        self.exercise_date.setObjectName("exercise_date")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.exercise_date)
        self.amountLabel = QtWidgets.QLabel(parent=AddExerciseDialog)
        self.amountLabel.setObjectName("amountLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.amountLabel)
        self.duration = QtWidgets.QLineEdit(parent=AddExerciseDialog)
        self.duration.setObjectName("duration")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.duration)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_add_exercise = QtWidgets.QPushButton(parent=AddExerciseDialog)
        self.btn_add_exercise.setMinimumSize(QtCore.QSize(70, 25))
        self.btn_add_exercise.setStyleSheet("QPushButton {\n"
"    background-color: #2ecc71;\n"
"    color: #fff;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.btn_add_exercise.setObjectName("btn_add_exercise")
        self.horizontalLayout_3.addWidget(self.btn_add_exercise)
        self.btn_cancel = QtWidgets.QPushButton(parent=AddExerciseDialog)
        self.btn_cancel.setMinimumSize(QtCore.QSize(70, 25))
        self.btn_cancel.setStyleSheet("QPushButton {\n"
"    background-color: #585858;\n"
"    color: #fff;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}")
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_3.addWidget(self.btn_cancel)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_3)
        self.timeLabel = QtWidgets.QLabel(parent=AddExerciseDialog)
        self.timeLabel.setObjectName("timeLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.timeLabel)
        self.exercise_time = QtWidgets.QTimeEdit(parent=AddExerciseDialog)
        self.exercise_time.setObjectName("exercise_time")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.exercise_time)
        self.verticalLayout.addLayout(self.formLayout)

        self.retranslateUi(AddExerciseDialog)
        QtCore.QMetaObject.connectSlotsByName(AddExerciseDialog)

    def retranslateUi(self, AddExerciseDialog):
        _translate = QtCore.QCoreApplication.translate
        AddExerciseDialog.setWindowTitle(_translate("AddExerciseDialog", "Thêm hoạt động thể chất"))
        self.titleLabel.setText(_translate("AddExerciseDialog", "Thêm hoạt động thể chất"))
        self.categoryLabel_2.setText(_translate("AddExerciseDialog", "Loại hoạt động:"))
        self.activity_type.setPlaceholderText(_translate("AddExerciseDialog", "Nhập loại hoạt động"))
        self.dateLabel.setText(_translate("AddExerciseDialog", "Ngày hoạt động:"))
        self.exercise_date.setDisplayFormat(_translate("AddExerciseDialog", "dd/MM/yyyy"))
        self.amountLabel.setText(_translate("AddExerciseDialog", "Thời gian (phút)"))
        self.duration.setPlaceholderText(_translate("AddExerciseDialog", "Nhập thời gian"))
        self.btn_add_exercise.setText(_translate("AddExerciseDialog", "Thêm"))
        self.btn_cancel.setText(_translate("AddExerciseDialog", "Hủy"))
        self.timeLabel.setText(_translate("AddExerciseDialog", "Giờ hoạt động:"))
        self.exercise_time.setDisplayFormat(_translate("AddExerciseDialog", "hh:mm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddExerciseDialog = QtWidgets.QDialog()
    ui = Ui_AddExerciseDialog()
    ui.setupUi(AddExerciseDialog)
    AddExerciseDialog.show()
    sys.exit(app.exec())
