# Form implementation generated from reading ui file 'add_customer.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddCustomerDialog(object):
    def setupUi(self, AddCustomerDialog):
        AddCustomerDialog.setObjectName("AddCustomerDialog")
        AddCustomerDialog.resize(330, 154)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddCustomerDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=AddCustomerDialog)
        self.titleLabel.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("font-weight: bold;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.categoryLabel_2 = QtWidgets.QLabel(parent=AddCustomerDialog)
        self.categoryLabel_2.setObjectName("categoryLabel_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.categoryLabel_2)
        self.name = QtWidgets.QLineEdit(parent=AddCustomerDialog)
        self.name.setObjectName("name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.name)
        self.amountLabel = QtWidgets.QLabel(parent=AddCustomerDialog)
        self.amountLabel.setObjectName("amountLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.amountLabel)
        self.phone_number = QtWidgets.QLineEdit(parent=AddCustomerDialog)
        self.phone_number.setObjectName("phone_number")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.phone_number)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_add_customer = QtWidgets.QPushButton(parent=AddCustomerDialog)
        self.btn_add_customer.setMinimumSize(QtCore.QSize(70, 25))
        self.btn_add_customer.setStyleSheet("QPushButton {\n"
"    background-color: #2ecc71;\n"
"    color: #fff;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.btn_add_customer.setObjectName("btn_add_customer")
        self.horizontalLayout_3.addWidget(self.btn_add_customer)
        self.btn_cancel = QtWidgets.QPushButton(parent=AddCustomerDialog)
        self.btn_cancel.setMinimumSize(QtCore.QSize(70, 25))
        self.btn_cancel.setStyleSheet("QPushButton {\n"
"    background-color: #585858;\n"
"    color: #fff;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}")
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_3.addWidget(self.btn_cancel)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.formLayout)

        self.retranslateUi(AddCustomerDialog)
        QtCore.QMetaObject.connectSlotsByName(AddCustomerDialog)

    def retranslateUi(self, AddCustomerDialog):
        _translate = QtCore.QCoreApplication.translate
        AddCustomerDialog.setWindowTitle(_translate("AddCustomerDialog", "Thêm khách hàng"))
        self.titleLabel.setText(_translate("AddCustomerDialog", "Thêm khác hàng"))
        self.categoryLabel_2.setText(_translate("AddCustomerDialog", "Tên:"))
        self.name.setPlaceholderText(_translate("AddCustomerDialog", "Nhập tên"))
        self.amountLabel.setText(_translate("AddCustomerDialog", "Số điện thoại:"))
        self.phone_number.setPlaceholderText(_translate("AddCustomerDialog", "Nhập số điện thoại"))
        self.btn_add_customer.setText(_translate("AddCustomerDialog", "Thêm"))
        self.btn_cancel.setText(_translate("AddCustomerDialog", "Hủy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddCustomerDialog = QtWidgets.QDialog()
    ui = Ui_AddCustomerDialog()
    ui.setupUi(AddCustomerDialog)
    AddCustomerDialog.show()
    sys.exit(app.exec())
