# Form implementation generated from reading ui file 'add_feeding.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddFeedingDialog(object):
    def setupUi(self, AddFeedingDialog):
        AddFeedingDialog.setObjectName("AddFeedingDialog")
        AddFeedingDialog.resize(330, 206)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddFeedingDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl = QtWidgets.QLabel(parent=AddFeedingDialog)
        self.lbl.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl.setFont(font)
        self.lbl.setStyleSheet("font-weight: bold;")
        self.lbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl.setObjectName("lbl")
        self.verticalLayout.addWidget(self.lbl)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.categoryLabel_2 = QtWidgets.QLabel(parent=AddFeedingDialog)
        self.categoryLabel_2.setObjectName("categoryLabel_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.categoryLabel_2)
        self.food_type = QtWidgets.QLineEdit(parent=AddFeedingDialog)
        self.food_type.setObjectName("food_type")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.food_type)
        self.dateLabel = QtWidgets.QLabel(parent=AddFeedingDialog)
        self.dateLabel.setObjectName("dateLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.dateLabel)
        self.feeding_date = QtWidgets.QDateEdit(parent=AddFeedingDialog)
        self.feeding_date.setCalendarPopup(True)
        self.feeding_date.setObjectName("feeding_date")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.feeding_date)
        self.amountLabel = QtWidgets.QLabel(parent=AddFeedingDialog)
        self.amountLabel.setObjectName("amountLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.amountLabel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_add_feeding = QtWidgets.QPushButton(parent=AddFeedingDialog)
        self.btn_add_feeding.setMinimumSize(QtCore.QSize(70, 25))
        self.btn_add_feeding.setStyleSheet("QPushButton {\n"
"    background-color: #2ecc71;\n"
"    color: #fff;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.btn_add_feeding.setObjectName("btn_add_feeding")
        self.horizontalLayout_3.addWidget(self.btn_add_feeding)
        self.btn_cancel = QtWidgets.QPushButton(parent=AddFeedingDialog)
        self.btn_cancel.setMinimumSize(QtCore.QSize(70, 25))
        self.btn_cancel.setStyleSheet("QPushButton {\n"
"    background-color: #585858;\n"
"    color: #fff;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}")
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_3.addWidget(self.btn_cancel)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_3)
        self.quantity = QtWidgets.QLineEdit(parent=AddFeedingDialog)
        self.quantity.setText("")
        self.quantity.setObjectName("quantity")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.quantity)
        self.timeLabel = QtWidgets.QLabel(parent=AddFeedingDialog)
        self.timeLabel.setObjectName("timeLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.timeLabel)
        self.feeding_time = QtWidgets.QTimeEdit(parent=AddFeedingDialog)
        self.feeding_time.setObjectName("feeding_time")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.feeding_time)
        self.verticalLayout.addLayout(self.formLayout)

        self.retranslateUi(AddFeedingDialog)
        QtCore.QMetaObject.connectSlotsByName(AddFeedingDialog)

    def retranslateUi(self, AddFeedingDialog):
        _translate = QtCore.QCoreApplication.translate
        AddFeedingDialog.setWindowTitle(_translate("AddFeedingDialog", "Thêm chế độ ăn uống"))
        self.lbl.setText(_translate("AddFeedingDialog", "Thêm chế độ ăn uống"))
        self.categoryLabel_2.setText(_translate("AddFeedingDialog", "Loại thức ăn:"))
        self.food_type.setPlaceholderText(_translate("AddFeedingDialog", "Nhập loại thức ăn"))
        self.dateLabel.setText(_translate("AddFeedingDialog", "Ngày ăn:"))
        self.feeding_date.setDisplayFormat(_translate("AddFeedingDialog", "dd/MM/yyyy"))
        self.amountLabel.setText(_translate("AddFeedingDialog", "Trọng lượng:"))
        self.btn_add_feeding.setText(_translate("AddFeedingDialog", "Thêm"))
        self.btn_cancel.setText(_translate("AddFeedingDialog", "Hủy"))
        self.quantity.setPlaceholderText(_translate("AddFeedingDialog", "Nhập trọng lượng"))
        self.timeLabel.setText(_translate("AddFeedingDialog", "Thời gian ăn:"))
        self.feeding_time.setDisplayFormat(_translate("AddFeedingDialog", "hh:mm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddFeedingDialog = QtWidgets.QDialog()
    ui = Ui_AddFeedingDialog()
    ui.setupUi(AddFeedingDialog)
    AddFeedingDialog.show()
    sys.exit(app.exec())
