# Form implementation generated from reading ui file 'add_pet.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddPetDialog(object):
    def setupUi(self, AddPetDialog):
        AddPetDialog.setObjectName("AddPetDialog")
        AddPetDialog.resize(330, 482)
        AddPetDialog.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(AddPetDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=AddPetDialog)
        self.titleLabel.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("font-weight: bold;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.birthday = QtWidgets.QLabel(parent=AddPetDialog)
        self.birthday.setObjectName("birthday")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.birthday)
        self.name = QtWidgets.QLineEdit(parent=AddPetDialog)
        self.name.setObjectName("name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.name)
        self.dateLabel = QtWidgets.QLabel(parent=AddPetDialog)
        self.dateLabel.setObjectName("dateLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.dateLabel)
        self.birth_date = QtWidgets.QDateEdit(parent=AddPetDialog)
        self.birth_date.setCalendarPopup(True)
        self.birth_date.setObjectName("birth_date")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.birth_date)
        self.amountLabel = QtWidgets.QLabel(parent=AddPetDialog)
        self.amountLabel.setObjectName("amountLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.amountLabel)
        self.detailsLabel = QtWidgets.QLabel(parent=AddPetDialog)
        self.detailsLabel.setObjectName("detailsLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.detailsLabel)
        self.special_features = QtWidgets.QTextEdit(parent=AddPetDialog)
        self.special_features.setObjectName("special_features")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.special_features)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_add_pet = QtWidgets.QPushButton(parent=AddPetDialog)
        self.btn_add_pet.setMinimumSize(QtCore.QSize(70, 25))
        self.btn_add_pet.setStyleSheet("QPushButton {\n"
"    background-color: #2ecc71;\n"
"    color: #fff;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.btn_add_pet.setObjectName("btn_add_pet")
        self.horizontalLayout_3.addWidget(self.btn_add_pet)
        self.btn_cancel = QtWidgets.QPushButton(parent=AddPetDialog)
        self.btn_cancel.setMinimumSize(QtCore.QSize(70, 25))
        self.btn_cancel.setStyleSheet("QPushButton {\n"
"    background-color: #585858;\n"
"    color: #fff;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}")
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_3.addWidget(self.btn_cancel)
        self.formLayout.setLayout(8, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_3)
        self.categoryLabel_3 = QtWidgets.QLabel(parent=AddPetDialog)
        self.categoryLabel_3.setObjectName("categoryLabel_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.categoryLabel_3)
        self.breed = QtWidgets.QLineEdit(parent=AddPetDialog)
        self.breed.setObjectName("breed")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.breed)
        self.color = QtWidgets.QLineEdit(parent=AddPetDialog)
        self.color.setObjectName("color")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.color)
        self.amountLabel_2 = QtWidgets.QLabel(parent=AddPetDialog)
        self.amountLabel_2.setObjectName("amountLabel_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.amountLabel_2)
        self.weight = QtWidgets.QLineEdit(parent=AddPetDialog)
        self.weight.setObjectName("weight")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.weight)
        self.amountLabel_3 = QtWidgets.QLabel(parent=AddPetDialog)
        self.amountLabel_3.setObjectName("amountLabel_3")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.amountLabel_3)
        self.length = QtWidgets.QLineEdit(parent=AddPetDialog)
        self.length.setObjectName("length")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.length)
        self.amountLabel_4 = QtWidgets.QLabel(parent=AddPetDialog)
        self.amountLabel_4.setObjectName("amountLabel_4")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.amountLabel_4)
        self.height = QtWidgets.QLineEdit(parent=AddPetDialog)
        self.height.setObjectName("height")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.height)
        self.verticalLayout.addLayout(self.formLayout)

        self.retranslateUi(AddPetDialog)
        QtCore.QMetaObject.connectSlotsByName(AddPetDialog)

    def retranslateUi(self, AddPetDialog):
        _translate = QtCore.QCoreApplication.translate
        AddPetDialog.setWindowTitle(_translate("AddPetDialog", "Thêm thú cưng"))
        self.titleLabel.setText(_translate("AddPetDialog", "Thêm thú cưng"))
        self.birthday.setText(_translate("AddPetDialog", "Tên:"))
        self.name.setPlaceholderText(_translate("AddPetDialog", "Nhập tên"))
        self.dateLabel.setText(_translate("AddPetDialog", "Ngày sinh:"))
        self.birth_date.setDisplayFormat(_translate("AddPetDialog", "dd/MM/yyyy"))
        self.amountLabel.setText(_translate("AddPetDialog", "Màu sắc:"))
        self.detailsLabel.setText(_translate("AddPetDialog", "Mô tả:"))
        self.special_features.setPlaceholderText(_translate("AddPetDialog", "Nhập mô tả..."))
        self.btn_add_pet.setText(_translate("AddPetDialog", "Thêm"))
        self.btn_cancel.setText(_translate("AddPetDialog", "Hủy"))
        self.categoryLabel_3.setText(_translate("AddPetDialog", "Giống loài:"))
        self.breed.setPlaceholderText(_translate("AddPetDialog", "Nhập giống loài"))
        self.color.setPlaceholderText(_translate("AddPetDialog", "Nhập màu sắc"))
        self.amountLabel_2.setText(_translate("AddPetDialog", "Cân nặng"))
        self.weight.setPlaceholderText(_translate("AddPetDialog", "Nhập cân nặng"))
        self.amountLabel_3.setText(_translate("AddPetDialog", "Chiều dài:"))
        self.length.setPlaceholderText(_translate("AddPetDialog", "Nhập chiều dài"))
        self.amountLabel_4.setText(_translate("AddPetDialog", "Chiều cao:"))
        self.height.setPlaceholderText(_translate("AddPetDialog", "Nhập chiều cao"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddPetDialog = QtWidgets.QDialog()
    ui = Ui_AddPetDialog()
    ui.setupUi(AddPetDialog)
    AddPetDialog.show()
    sys.exit(app.exec())
