# Form implementation generated from reading ui file 'edit_feeding.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EditFeedingDialog(object):
    def setupUi(self, EditFeedingDialog):
        EditFeedingDialog.setObjectName("EditFeedingDialog")
        EditFeedingDialog.resize(330, 206)
        self.verticalLayout = QtWidgets.QVBoxLayout(EditFeedingDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl = QtWidgets.QLabel(parent=EditFeedingDialog)
        self.lbl.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl.setFont(font)
        self.lbl.setStyleSheet("font-weight: bold;")
        self.lbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl.setObjectName("lbl")
        self.verticalLayout.addWidget(self.lbl)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.categoryLabel_2 = QtWidgets.QLabel(parent=EditFeedingDialog)
        self.categoryLabel_2.setObjectName("categoryLabel_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.categoryLabel_2)
        self.food_type = QtWidgets.QLineEdit(parent=EditFeedingDialog)
        self.food_type.setObjectName("food_type")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.food_type)
        self.dateLabel = QtWidgets.QLabel(parent=EditFeedingDialog)
        self.dateLabel.setObjectName("dateLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.dateLabel)
        self.feeding_date = QtWidgets.QDateEdit(parent=EditFeedingDialog)
        self.feeding_date.setCalendarPopup(True)
        self.feeding_date.setObjectName("feeding_date")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.feeding_date)
        self.amountLabel = QtWidgets.QLabel(parent=EditFeedingDialog)
        self.amountLabel.setObjectName("amountLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.amountLabel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_edit_feeding = QtWidgets.QPushButton(parent=EditFeedingDialog)
        self.btn_edit_feeding.setMinimumSize(QtCore.QSize(70, 25))
        self.btn_edit_feeding.setStyleSheet("QPushButton {\n"
"    background-color: #2ecc71;\n"
"    color: #fff;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.btn_edit_feeding.setObjectName("btn_edit_feeding")
        self.horizontalLayout_3.addWidget(self.btn_edit_feeding)
        self.btn_cancel = QtWidgets.QPushButton(parent=EditFeedingDialog)
        self.btn_cancel.setMinimumSize(QtCore.QSize(70, 25))
        self.btn_cancel.setStyleSheet("QPushButton {\n"
"    background-color: #585858;\n"
"    color: #fff;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}")
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_3.addWidget(self.btn_cancel)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_3)
        self.quantity = QtWidgets.QLineEdit(parent=EditFeedingDialog)
        self.quantity.setText("")
        self.quantity.setObjectName("quantity")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.quantity)
        self.timeLabel = QtWidgets.QLabel(parent=EditFeedingDialog)
        self.timeLabel.setObjectName("timeLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.timeLabel)
        self.feeding_time = QtWidgets.QTimeEdit(parent=EditFeedingDialog)
        self.feeding_time.setObjectName("feeding_time")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.feeding_time)
        self.verticalLayout.addLayout(self.formLayout)

        self.retranslateUi(EditFeedingDialog)
        QtCore.QMetaObject.connectSlotsByName(EditFeedingDialog)

    def retranslateUi(self, EditFeedingDialog):
        _translate = QtCore.QCoreApplication.translate
        EditFeedingDialog.setWindowTitle(_translate("EditFeedingDialog", "Sửa chế độ ăn uống"))
        self.lbl.setText(_translate("EditFeedingDialog", "Sửa chế độ ăn uống"))
        self.categoryLabel_2.setText(_translate("EditFeedingDialog", "Loại thức ăn:"))
        self.food_type.setPlaceholderText(_translate("EditFeedingDialog", "Nhập loại thức ăn"))
        self.dateLabel.setText(_translate("EditFeedingDialog", "Ngày ăn:"))
        self.feeding_date.setDisplayFormat(_translate("EditFeedingDialog", "dd/MM/yyyy"))
        self.amountLabel.setText(_translate("EditFeedingDialog", "Trọng lượng:"))
        self.btn_edit_feeding.setText(_translate("EditFeedingDialog", "Sửa"))
        self.btn_cancel.setText(_translate("EditFeedingDialog", "Hủy"))
        self.quantity.setPlaceholderText(_translate("EditFeedingDialog", "Nhập trọng lượng"))
        self.timeLabel.setText(_translate("EditFeedingDialog", "Thời gian ăn:"))
        self.feeding_time.setDisplayFormat(_translate("EditFeedingDialog", "hh:mm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditFeedingDialog = QtWidgets.QDialog()
    ui = Ui_EditFeedingDialog()
    ui.setupUi(EditFeedingDialog)
    EditFeedingDialog.show()
    sys.exit(app.exec())
