# Form implementation generated from reading ui file 'edit_expense.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EditExpenseDialog(object):
    def setupUi(self, EditExpenseDialog):
        EditExpenseDialog.setObjectName("EditExpenseDialog")
        EditExpenseDialog.resize(330, 374)
        self.verticalLayout = QtWidgets.QVBoxLayout(EditExpenseDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=EditExpenseDialog)
        self.titleLabel.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("font-weight: bold;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.categoryLabel_2 = QtWidgets.QLabel(parent=EditExpenseDialog)
        self.categoryLabel_2.setObjectName("categoryLabel_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.categoryLabel_2)
        self.expense_type = QtWidgets.QLineEdit(parent=EditExpenseDialog)
        self.expense_type.setObjectName("expense_type")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.expense_type)
        self.dateLabel = QtWidgets.QLabel(parent=EditExpenseDialog)
        self.dateLabel.setObjectName("dateLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.dateLabel)
        self.expense_date = QtWidgets.QDateEdit(parent=EditExpenseDialog)
        self.expense_date.setCalendarPopup(True)
        self.expense_date.setObjectName("expense_date")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.expense_date)
        self.amountLabel = QtWidgets.QLabel(parent=EditExpenseDialog)
        self.amountLabel.setObjectName("amountLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.amountLabel)
        self.amount = QtWidgets.QDoubleSpinBox(parent=EditExpenseDialog)
        self.amount.setDecimals(0)
        self.amount.setMaximum(1000000000.0)
        self.amount.setProperty("groupSeparatorShown", True)
        self.amount.setObjectName("amount")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.amount)
        self.detailsLabel = QtWidgets.QLabel(parent=EditExpenseDialog)
        self.detailsLabel.setObjectName("detailsLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.detailsLabel)
        self.description = QtWidgets.QTextEdit(parent=EditExpenseDialog)
        self.description.setObjectName("description")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.description)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_edit_expense = QtWidgets.QPushButton(parent=EditExpenseDialog)
        self.btn_edit_expense.setMinimumSize(QtCore.QSize(70, 25))
        self.btn_edit_expense.setStyleSheet("QPushButton {\n"
"    background-color: #2ecc71;\n"
"    color: #fff;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.btn_edit_expense.setObjectName("btn_edit_expense")
        self.horizontalLayout_3.addWidget(self.btn_edit_expense)
        self.btn_cancel = QtWidgets.QPushButton(parent=EditExpenseDialog)
        self.btn_cancel.setMinimumSize(QtCore.QSize(70, 25))
        self.btn_cancel.setStyleSheet("QPushButton {\n"
"    background-color: #585858;\n"
"    color: #fff;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}")
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_3.addWidget(self.btn_cancel)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_3)
        self.timeLabel = QtWidgets.QLabel(parent=EditExpenseDialog)
        self.timeLabel.setObjectName("timeLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.timeLabel)
        self.expense_time = QtWidgets.QTimeEdit(parent=EditExpenseDialog)
        self.expense_time.setObjectName("expense_time")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.expense_time)
        self.verticalLayout.addLayout(self.formLayout)

        self.retranslateUi(EditExpenseDialog)
        QtCore.QMetaObject.connectSlotsByName(EditExpenseDialog)

    def retranslateUi(self, EditExpenseDialog):
        _translate = QtCore.QCoreApplication.translate
        EditExpenseDialog.setWindowTitle(_translate("EditExpenseDialog", "Sửa chi phí"))
        self.titleLabel.setText(_translate("EditExpenseDialog", "Sửa chi phí"))
        self.categoryLabel_2.setText(_translate("EditExpenseDialog", "Loại chi phí:"))
        self.expense_type.setPlaceholderText(_translate("EditExpenseDialog", "Nhập loại chi phí"))
        self.dateLabel.setText(_translate("EditExpenseDialog", "Ngày phát sinh:"))
        self.expense_date.setDisplayFormat(_translate("EditExpenseDialog", "dd/MM/yyyy"))
        self.amountLabel.setText(_translate("EditExpenseDialog", "Số tiền:"))
        self.amount.setSuffix(_translate("EditExpenseDialog", " VNĐ"))
        self.detailsLabel.setText(_translate("EditExpenseDialog", "Chi tiết:"))
        self.description.setPlaceholderText(_translate("EditExpenseDialog", "Nhập chi tiết..."))
        self.btn_edit_expense.setText(_translate("EditExpenseDialog", "Sửa"))
        self.btn_cancel.setText(_translate("EditExpenseDialog", "Hủy"))
        self.timeLabel.setText(_translate("EditExpenseDialog", "Thời gian:"))
        self.expense_time.setDisplayFormat(_translate("EditExpenseDialog", "hh:mm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditExpenseDialog = QtWidgets.QDialog()
    ui = Ui_EditExpenseDialog()
    ui.setupUi(EditExpenseDialog)
    EditExpenseDialog.show()
    sys.exit(app.exec())
