# Form implementation generated from reading ui file 'edit_appointment.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EditAppointmentDialog(object):
    def setupUi(self, EditAppointmentDialog):
        EditAppointmentDialog.setObjectName("EditAppointmentDialog")
        EditAppointmentDialog.resize(330, 353)
        self.verticalLayout = QtWidgets.QVBoxLayout(EditAppointmentDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=EditAppointmentDialog)
        self.titleLabel.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("font-weight: bold;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.dateLabel = QtWidgets.QLabel(parent=EditAppointmentDialog)
        self.dateLabel.setObjectName("dateLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.dateLabel)
        self.appointment_date = QtWidgets.QDateEdit(parent=EditAppointmentDialog)
        self.appointment_date.setCalendarPopup(True)
        self.appointment_date.setObjectName("appointment_date")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.appointment_date)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_edit_appointment = QtWidgets.QPushButton(parent=EditAppointmentDialog)
        self.btn_edit_appointment.setMinimumSize(QtCore.QSize(70, 25))
        self.btn_edit_appointment.setStyleSheet("QPushButton {\n"
"    background-color: #2ecc71;\n"
"    color: #fff;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.btn_edit_appointment.setObjectName("btn_edit_appointment")
        self.horizontalLayout_3.addWidget(self.btn_edit_appointment)
        self.btn_cancel = QtWidgets.QPushButton(parent=EditAppointmentDialog)
        self.btn_cancel.setMinimumSize(QtCore.QSize(70, 25))
        self.btn_cancel.setStyleSheet("QPushButton {\n"
"    background-color: #585858;\n"
"    color: #fff;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}")
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_3.addWidget(self.btn_cancel)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_3)
        self.timeLabel = QtWidgets.QLabel(parent=EditAppointmentDialog)
        self.timeLabel.setObjectName("timeLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.timeLabel)
        self.appointment_time = QtWidgets.QTimeEdit(parent=EditAppointmentDialog)
        self.appointment_time.setObjectName("appointment_time")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.appointment_time)
        self.purpose = QtWidgets.QTextEdit(parent=EditAppointmentDialog)
        self.purpose.setObjectName("purpose")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.purpose)
        self.timeLabel_2 = QtWidgets.QLabel(parent=EditAppointmentDialog)
        self.timeLabel_2.setObjectName("timeLabel_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.timeLabel_2)
        self.verticalLayout.addLayout(self.formLayout)

        self.retranslateUi(EditAppointmentDialog)
        QtCore.QMetaObject.connectSlotsByName(EditAppointmentDialog)

    def retranslateUi(self, EditAppointmentDialog):
        _translate = QtCore.QCoreApplication.translate
        EditAppointmentDialog.setWindowTitle(_translate("EditAppointmentDialog", "Sửa lịch hẹn"))
        self.titleLabel.setText(_translate("EditAppointmentDialog", "Sửa lịch hẹn"))
        self.dateLabel.setText(_translate("EditAppointmentDialog", "Ngày hẹn:"))
        self.appointment_date.setDisplayFormat(_translate("EditAppointmentDialog", "dd/MM/yyyy"))
        self.btn_edit_appointment.setText(_translate("EditAppointmentDialog", "Sửa"))
        self.btn_cancel.setText(_translate("EditAppointmentDialog", "Hủy"))
        self.timeLabel.setText(_translate("EditAppointmentDialog", "Thời gian hẹn:"))
        self.appointment_time.setDisplayFormat(_translate("EditAppointmentDialog", "hh:mm"))
        self.purpose.setPlaceholderText(_translate("EditAppointmentDialog", "Nhập mục đích cuộc hẹn..."))
        self.timeLabel_2.setText(_translate("EditAppointmentDialog", "Mục đích"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditAppointmentDialog = QtWidgets.QDialog()
    ui = Ui_EditAppointmentDialog()
    ui.setupUi(EditAppointmentDialog)
    EditAppointmentDialog.show()
    sys.exit(app.exec())
